"""Referral Hunter agent for the Hoolulu Factory.

Generated by the Hoolulu Agent. Wire it into a stage by importing it from
``agent/factory.py`` or calling it from ``agent/tools.py``.
"""

import os
import sys
from datetime import datetime

# Allow running this file directly: put the repository root on sys.path so the
# ``agent`` package resolves no matter where the script is launched from.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agent import factory


def run(lead):
    """Process one lead and return the fields to write back."""
    return {
        "notes": ((lead.get("notes") or "") + " | handled by referral_hunter").strip(" |"),
        "updated_at": datetime.now().isoformat(timespec="seconds"),
    }


def run_all(status="SCORED"):
    """Process every lead currently sitting in ``status``."""
    results = []
    conn = factory.connect()
    try:
        rows = [dict(r) for r in conn.execute(
            "SELECT * FROM leads WHERE upper(status) = ?", (status.upper(),)
        )]
        for lead in rows:
            update = run(lead)
            sets = ", ".join(f"{k} = ?" for k in update)
            conn.execute(
                f"UPDATE leads SET {sets} WHERE id = ?",
                (*update.values(), lead["id"]),
            )
            results.append({"business": lead["business"], **update})
        conn.commit()
    finally:
        conn.close()
    return {"agent": "Referral Hunter", "processed": len(results), "results": results}


if __name__ == "__main__":
    output = run_all()
    print(f"{output['agent']} processed {output['processed']} lead(s)")
    for item in output["results"]:
        print(" -", item["business"])
